### ISSUE TITLE
Is any literature about the ekf's model/measurement system here ?

### ISSUE THREAD

**Issue by didididida** [balamuruganky/EKF_IMU_GPS#2]
Hello,

Is there any literature or paper about the model system here, I am not very clear about how the Jaccobi function update and the part of state update about the bias.

Thanks

**Comment by balamuruganky** [comment]
@didididida : Please go through https://pythonrobotics.readthedocs.io/en/latest/modules/localization/localization.html#extended-kalman-filter-localization.

**Comment by balamuruganky** [comment]
This thread is inactive since long. I assume that the question is answered.
